---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    groups:
      docker:
        patterns:
          - "*"
    target-branch: master

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    target-branch: master
