---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    target-branch: v1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: v1
