---
name: 'Latexmk'
description: 'Use the Latex in your Github Actions.'

inputs:
  format:
    description: "File format to generate"
    required: true
    default: pdf

  filename:
    description: "Source file name"
    required: false
    default: main.tex

runs:
  using: 'docker'
  image: 'docker://ghcr.io/hspaans/latexmk-action:1.1.3'
  env:
    ACTION_FORMAT: ${{ inputs.format }}
    ACTION_FILENAME: ${{ inputs.filename }}

branding:
  icon: 'book'
  color: 'gray-dark'
