---
name: 'Latexmk'
description: 'Use the Latex in your Github Actions.'

inputs:
  format:
    description: "File format to generate"
    required: true
    default: pdf

  filename:
    description: "Source file name"
    required: false
    default: main.tex

  arguments:
    description: "Arguments passed to latexmk"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACTION_FORMAT: ${{ inputs.format }}
    ACTION_FILENAME: ${{ inputs.filename }}
    ACTION_ARGS: ${{ inputs.arguments }}

branding:
  icon: 'book'
  color: 'gray-dark'
