---
name: CI

on:
  # Run tests for any PRs.
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    needs: lint
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  Anchore-Build-Scan:
    needs: test
    name: Anchore-Build-Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Run the local Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@v2
        with:
          image: "localbuild/testimage:latest"
          acs-report-enable: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
