---
name: Container CI

on:
  pull_request:
  schedule:
    - cron: '20 20 8 * *'

jobs:
  reusable-workflow:
    name: Reusable workflow
    uses: hspaans/.github/.github/workflows/container-ci.yml@master
