---
name: Container Release

on:
  push:
    branches:
      - master
      - v*
    tags:
      - v*

jobs:
  reusable-workflow:
    name: Reusable workflow
    uses: hspaans/.github/.github/workflows/container-release.yml@v2024.12.14-1
    with:
      actor: ${{ github.actor }}
      platforms: linux/amd64,linux/arm64
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}
